import Event from "Scripts/Events"
import {CAT_FACTS} from "./CatFacts"

/**
 * Serves cat facts from a local, bundled dataset — no internet required.
 *
 * The class name is kept as `FetchCatFacts` (and the file unchanged) so the
 * existing Scene component reference and CatFactAnimator's `fetchCatFacts`
 * @input binding stay valid. It no longer fetches anything over the network;
 * `getCatFacts()` picks a random fact locally and fires the same event.
 *
 * Optional offline narration: assign an AudioComponent and the fact_XX.mp3
 * clips (generated by tools/generate_audio.py) to `factAudioTracks`, in the
 * same order as CAT_FACTS. On each fact, the matching clip is played. If either
 * input is left unset the Lens is silent — behaviour is otherwise unchanged.
 *
 * Narration clips never overlap: a new clip always stops the current one before
 * it starts. With `letClipFinish` enabled, a new tip is ignored entirely until
 * the current clip has finished, so every tip plays start-to-finish in order.
 */
@component
export class FetchCatFacts extends BaseScriptComponent {
  // Shared player used for all narration clips. Use a DEDICATED Audio component
  // (not one shared with meows/SFX) so nothing else can step on the narration.
  @input
  @allowUndefined
  audioComponent: AudioComponent

  // Narration clips, index-aligned to CAT_FACTS (fact_00.mp3 → CAT_FACTS[0], …).
  @input
  @allowUndefined
  factAudioTracks: AudioTrackAsset[]

  // If true, ignore new tips while a clip is still playing (each tip plays fully
  // before the next). If false (default), a new tip interrupts — latest wins.
  @input
  letClipFinish: boolean

  catFactReceived: Event<string>

  // Index of the fact shown last, so we never repeat the same fact twice in a row.
  private lastIndex = -1

  onAwake() {
    this.catFactReceived = new Event<string>()
  }

  public getCatFacts() {
    // Don't step on a clip that's still speaking, if configured to wait it out.
    if (this.letClipFinish && this.isNarrationPlaying()) {
      return
    }
    const index = this.pickRandomIndex()
    this.playFactAudio(index)
    this.catFactReceived.invoke(index < 0 ? "" : CAT_FACTS[index])
  }

  private isNarrationPlaying(): boolean {
    return !!this.audioComponent && this.audioComponent.isPlaying()
  }

  private pickRandomIndex(): number {
    if (CAT_FACTS.length === 0) {
      return -1
    }
    if (CAT_FACTS.length === 1) {
      this.lastIndex = 0
      return 0
    }

    let index = Math.floor(Math.random() * CAT_FACTS.length)
    if (index === this.lastIndex) {
      index = (index + 1) % CAT_FACTS.length
    }
    this.lastIndex = index
    return index
  }

  // Play the narration clip that matches the chosen fact, if audio is configured.
  private playFactAudio(index: number) {
    if (!this.audioComponent || !this.factAudioTracks || index < 0) {
      return
    }
    const track = this.factAudioTracks[index]
    if (!track) {
      return
    }
    // Guarantee clips never overlap: fully stop the current one before starting
    // the next, so two tips can never be heard at the same time.
    if (this.audioComponent.isPlaying()) {
      this.audioComponent.stop(false)
    }
    this.audioComponent.audioTrack = track
    this.audioComponent.play(1)
  }
}
